language: python
python:
  - "2.7"
  - "pypy"
  - "3.2"
  - "3.3"
  - "3.4"
  - "3.5"
script:
  - pip install .
  - pip install -r requirements.txt
cache: apt
matrix:
  allow_failures:
    - python: pypy
